### ISSUE TITLE
AirPressure Formats.FLOAT ?

### ISSUE THREAD

**Issue by alexwala** [ebaauw/homebridge-lib#34]
Shouldn't AirPressure be Formats.FLOAT ?
see [Eve Weather](https://gist.github.com/simont77/3f4d4330fa55b83f8ca96388d9004e7d#eve-weather-16-bytes-in-total)
also in EVE App Air Pressure -> Measurements will be displayed with 1dp

**Comment by ebaauw** [comment]
The link you’re referring to lists the data format in the Eve history entry, which definitely is an integer value.  It it the pressure in hPa x 10, indeed suggesting the characteristic value could be float, with one decimal.

For my Eve Weather (latest version, with a Thread support), Eve only shows the pressure as integer value in hPa, but logs the history in 0.1 hPa.  Home+ shows the pressure in kPA (10 hPa), so that’s of no help either.  But HMCatalog actually shows the raw characteristic value with one decimal.

I don’t have any plugins that could actually use this increased precision.  OpenWeatherMap reports pressure as integer value in hPa, and the Zigbee Cluster Library also defines pressure as integer in hPa.  Some Xiaomi weather sensors actually have a 0.1 hPa resolution in the special attribute report, but the deCONZ API only reports the integer value.

**Comment by alexwala** [comment]
nice, will there be a new version of homebridge-lib ?

**Comment by ebaauw** [comment]
Of course.  I’m right in the middle of doing some other changes for Homebridge deCONZ, so it might take a little while.   I probably should have created a separate repo for the Eve characteristics, in hindsight.

**Comment by alexwala** [comment]
perfect ! thank you.

**Comment by ebaauw** [comment]
In v5.2.0.
